services:
  redis:
    image: redis:7.4-alpine
    ports: 
      - "6379:6379"
  web:
    build:
      context: .
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - redis